### ISSUE TITLE
Update Readme Link to Releases Page to New Repository (Also a release?)

### ISSUE THREAD

**Issue by dezren39** [Kyrremann/FreshKeebInLA#3]
https://github.com/Kyrremann/asetniop-typing-game/releases
I believe this was the old name before having rebranded?

I can submit a PR to update the link to,
https://github.com/Kyrremann/FreshKeebInLA/releases
, however a release with binaries would be needed in order for that to be useful. 🙂

Installing Love now to try this out! :-D

**Comment by Kyrremann** [comment]
Thanks, as mention in the PR, I'll add one more feature, and then I'll create release binaries for each of linux, osx, and windows.
